### ISSUE TITLE
Readme neu formatieren

### ISSUE THREAD

**Issue by zonky2** [ciaobello/c2gmanager#1]
warum Schreibst Du die Aufzählungen als "Qeuelltext" - hier einige Formatierungen für Markdown https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists

**Comment by ciaobello** [comment]
Lange ist es her ... aber ich habe es nun formatiert.

**Comment by ciaobello** [comment]
i close it ...
